[settings]
lockfile = true

[tools]
"github:composer/composer" = "latest"
lychee = "latest"

[tasks.check-links]
description = "Check links with lychee"
run = "lychee --no-progress './**/*.md' './src/**/*.php' './composer.json'"
